# Generated by Django 2.2.3 on 2019-08-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('KD', 'Kinder'), ('PR', 'Paperback'), ('HD', 'Hardcover')], default='PR', max_length=10),
        ),
    ]
