# Generated by Django 2.2.3 on 2019-07-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='cards',
        ),
    ]
