# Generated by Django 2.2.3 on 2019-07-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190719_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cards',
            new_name='Card',
        ),
    ]
