# Generated by Django 2.2.3 on 2019-07-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20190720_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ToDo', 'to-do'), ('InProgress', 'in-progress'), ('Done', 'done')], default='ToDo', max_length=250),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
